---
name: Pull request build

on:
  pull_request:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check PR title  
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "module.exports = { extends: ['@commitlint/config-conventional'] };" > commitlint.config.js
          npm i -g commitlint @commitlint/config-conventional
          echo "$TITLE" | commitlint
