---
name: Pull request build

on:
  pull_request:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm i -g commitlint @commitlint/config-conventional
          echo "${{ github.event.pull_request.title }}" | commitlint
